### PR TITLE
Add abort to autoload functions

### PR DESCRIPTION
**Pull request by alok**
Prevents user getting bugged with error messages if something fails.
Also recommended by `vint`.

### CODE REVIEW

**Comment by dbmrq** [comment]
Uhm, I'm not 100% sure about this. If something random fails wouldn't it be better for the user to get an error message so he can try to understand what happened? And if something fails consistently (have you ran into anything like that?) wouldn't it be batter to handle it with try/catch?

**Comment by Alok** [comment]
[I've gotten this error before](https://gist.github.com/Alok/aee501a96cb0800df878dfbdd73dbf2f). I *think* `abort` logs the error but doesn't bug the user.

**Comment by alok** [comment]
[I've gotten this error before](https://gist.github.com/Alok/aee501a96cb0800df878dfbdd73dbf2f). `abort` forces the function to halt when it encounters an error.

**Comment by dbmrq** [comment]
Uhm, that's weird… I don't see how `b:dittoMatchedwords` would turn out to be an invalid argument for `len()`. Can you reproduce this error somehow?

I'll take a better look at what's going on when I have the time, and also at those undefined variables, it should be easy to fix. And then I'll consider adding `abort`, but I think it would be better to go with try/catch where it's expected that something could fail, and to just let it fail when it's unexpected.

**Comment by dbmrq** [comment]
@Alok I think I fixed the errors there in your gist. If you still get anything like that please let me know here. For now I won't add the `abort`, but I'm still considering it, I'll keep it in mind.

**Pull request closed without merging**
